### ISSUE TITLE
Connecting to firestore database is not working

### ISSUE THREAD

**Issue by solstarz** [gdg-x/hoverboard#2321]
**Describe the bug**
When i deploy the app my schedule page is empty its not being linked to the firestoredatabase.
I've added a databasUrl in the firebase.ts with the url for the firestore database.
But while debugging i saw the url is changed to find data in the realtime database.

**To Reproduce**

Deploy the app to firebase and you will see that the schedule and speakers page will be empty.
No schedule and no active speakers.

**Expected behavior**
I would like to see the schedule and speakers

**Comment by abraham** [comment]
[`firebase.ts`](https://github.com/gdg-x/hoverboard/blob/main/src/firebase.ts#L6) dynamically loads the Firebase config from whichever firebase project you [selected](https://github.com/gdg-x/hoverboard/blob/main/docs/tutorials/01-configure-app.md) with `npx firebase use <projectid>`.

Look at the [Firebase functions logs](https://firebase.google.com/docs/functions/writing-and-viewing-logs#using_the_firebase_console) for errors and make sure [`config.schedule.enabled`](https://github.com/gdg-x/hoverboard/blob/main/docs/default-firebase-data.json#L67) is set to true.

**Comment by solstarz** [comment]
@abraham Thanks for your feedback.
This config.schedule.enabled is set to true, which is good.
npx firebase use (projectid) is used and connected to my projectid.
Firebase function logs shows no errors.

I think im over looking something, but not sure what...

**Comment by abraham** [comment]
Do any of the Firestore collections have any data in the [Firebase console](https://console.firebase.google.com/)?

- schedule
- sessions
- speakers
- generatedSchedule
- generatedSessions
- generatedSpeakers

**Comment by solstarz** [comment]
> 

I have the first 3 collections with data.
The last 3 are not present as collections in the firestore database..

**Comment by solstarz** [comment]
I did change a date in one of the scheduled collections and im now seeing the speakers appear..
But still no schedule.

These two collections are now present:

- generatedSessions
- generatedSpeakers

Do i have to make new schedule document for it to be picked up with the functions?

This firebase stuff is new to me, noob here...

**Comment by rlin-infotrust** [comment]
I am currently encountering this same problem where these collections aren't being generated in my remote Firestore:
```
generatedSchedule
generatedSessions
generatedSpeakers
```

The codebase I'm using has the fix made in https://github.com/gdg-x/hoverboard/pull/2324

I have this set in `default-firebase-data.json`:
```
    "schedule": {
      "enabled": true
    },
```

Any idea what might be wrong?  I do not see any errors when I run `$> firebase functions:log`
(The return is just: `"No log entries found."`)

Here is what my localhost and remote Firestore looks like.  For my Firestore rules, I have `test mode` currently enabled (`allow read, write: if true;`):

(Note:  I did add a debug line in `selectors.ts` and indeed see no data being returned from FS in that `fetchSpeakers` call (likely because `generatedSpeakers` is missing). 🤔)

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/93941848/214752657-d75bfef8-f31f-420a-9faa-493475619c31.png">

<img width="611" alt="image" src="https://user-images.githubusercontent.com/93941848/214753090-62c68201-756c-4744-85bb-64c2d08e7161.png">

<img width="206" alt="image" src="https://user-images.githubusercontent.com/93941848/214753248-a3a5688d-6ece-41d5-a22c-b43bad327363.png">
