### ISSUE TITLE
Corrupted content error on Firefox

### ISSUE THREAD

**Issue by scraly** [gdg-x/hoverboard#253]
Hi,
since we fork hoverboard for our 2017 devfest toulouse website, we have corrupted content error on Firefox and Firefox mobile.
It's very anoying and blocking to have an error each time we want to go to the website on Firefox. In order to not have the issue, we must do a ctrl+f5 and it's working, but we need to not have the issue.

Have you analyzed this issue? Do you know a permanent fix?

Thanks.

**Comment by ozasadnyy** [comment]
It was fixed a while ago in https://github.com/gdg-x/hoverboard/issues/149 (sw-precache bug https://github.com/GoogleChrome/sw-precache/issues/220). Seems like it is broken again :/

**Comment by scraly** [comment]
Here several print screen in order to help you with this bug:

<img width="1302" alt="3a8f7b5e-305c-11e7-9efb-1cf3d4a07acd" src="https://cloud.githubusercontent.com/assets/2543381/25771839/e7331eae-325c-11e7-84f6-c8d6a6095b75.png">

<img width="929" alt="3a88baee-305c-11e7-83f2-557728bbc1c7" src="https://cloud.githubusercontent.com/assets/2543381/25771841/e96b5056-325c-11e7-9a3e-516afc662f59.png">

Thanks

**Comment by anxolerd** [comment]
There is a similar problem in Google Chrome from dev and canary channel. Despite the message in the main window says that the page cannot be reached, the error in the console is the same:

```
The FetchEvent for "https://devfest.gdg.org.ua/" resulted in a network error response: a redirected response was used for a request whose redirect mode is not "follow".
Promise (async)
(anonymous) @ service-worker.js:213
Promise (async)
(anonymous) @ service-worker.js:212


GET https://devfest.gdg.org.ua/ net::ERR_FAILED                    https://devfest.gdg.org.ua/:1
```

The root of the problem seems to be in the following:
- Page with redirected response was cached with response flag `redirected` set to `true`
- On the second time page is loaded the fetch request with request mode `manual`. 
- We retrieve response from the cache with `redirected` flag set to `true`
- On the attempt to return such response fetch throws an error as it violates its [internal policies](https://bugs.chromium.org/p/chromium/issues/detail?id=658249)

Despite it seems as the bug of https://github.com/GoogleChrome/sw-precache/ I believe the part of the problem is in that how index page of hoverboard project is resolved (with redirect).

**Comment by davinkevin** [comment]
I work with @scraly and found the root cause of the problem... the `sw-precache` dependency defined in the `package.json` isn't used at all during the build, because it doesn't override the `polymer-build` dependency. 

After many try with NPM (v3 on my laptop), I choose to move to Yarn in order to help me thanks to the `yarn.lock` file. I just made a modification in the `yarn.lock` in order to change the `polymer-build -> sw-precache` version dependency. 

I think, the best solution would be to do a PR on the module `polymer-build` in order to ask them to update the `sw-precache` dep.

**Comment by davinkevin** [comment]
Glad to see the request already open in the `polymer-build` project => https://github.com/Polymer/polymer-build/issues/199

**Comment by ozasadnyy** [comment]
@davinkevin maybe it's better to send a PR? Would you like to create it?

**Comment by davinkevin** [comment]
@ozasadnyy PR Done (https://github.com/Polymer/polymer-build/pull/201) 

I've just updated the `package.json` and launch the tests... I can't do more on my side (I'm sadly not a pro on Polymer...)

**Comment by ozasadnyy** [comment]
@davinkevin you made a lot! Looks like in next few days we are going to have a fix :)

**Comment by ozasadnyy** [comment]
Thanks to everyone who took part in fixing this error!

**Comment by davinkevin** [comment]
Merged into our DevFest website and successfully deployed.

Thanks you all ;)
