### ISSUE TITLE
EACCES: permission denied, access '/app'

### ISSUE THREAD

**Issue by sagoyanfisic** [gdg-x/hoverboard#260]
I was installing the template, install the correct version of nodejs and when I run this error I could help

-- > npm run serve

> hoverboard@1.2.0 serve /home/skillstudentsorg/hoverboard
> gulp serve

/home/skillstudentsorg/hoverboard/gulpfile.js:34
  fragments: polymerJson.fragments.reduce((res, el) => [...res, prependPath(config.tempDirectory, el)], []),
                                                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/home/skillstudentsorg/hoverboard/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/skillstudentsorg/hoverboard/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/home/skillstudentsorg/hoverboard/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

npm ERR! Linux 4.8.0-54-generic
npm ERR! argv "/root/.nvm/versions/node/v4.4.7/bin/node" "/root/.nvm/versions/node/v4.4.7/bin/npm" "run" "serve"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! hoverboard@1.2.0 serve: `gulp serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hoverboard@1.2.0 serve script 'gulp serve'.
npm ERR! This is most likely a problem with the hoverboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hoverboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls hoverboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/skillstudentsorg/hoverboard/npm-debug.log

**Comment by misashi** [comment]
I had a similar issue. Try this fix, [https://github.com/gdg-x/hoverboard/tree/e38c68561fe41cb72d3b12b6a529c8d21efcee34](#252)
use the gulp build from there and see how it works for you.

**Comment by ozasadnyy** [comment]
@sagoyanfisic did you make any changes?

**Comment by anxolerd** [comment]
@sagoyanfisic it seems you are using an old version of node, which does not support ES6 spread operator, which is used in gulpfile.
According to [ES6 compatibility table](https://kangax.github.io/compat-table/es6/) this feature is supported in node 6.5.x and higher. Try to install it and try again with it.

As for the issue title (which is unrelated to the issue body), it seems the issue of EACCES happens because of security policies your machine has. Some stuff with docker mounting volumes and SELinux. Try to put SELinux in permissive mode before running docker commands:

```bash
# setenforce permissive
```

Please note, that this will lower the security policies on your machine, so use it only when you need this. And make sure you put your machine in the enforcing mode after you finished working with this project.

```bash
# setenforce enforcing
```

**Comment by cliveb** [comment]
I found Polymer v1.5.4 is a related project dependency. Thus if your gulp does not actually build after upgrading node. Check polymer version and upgrade.
 
$ polymer --version
$ npm install -g polymer-cli@1.5.4
