### ISSUE TITLE
good-map displays weird with zoom 18

### ISSUE THREAD

**Issue by MrCsabaToth** [gdg-x/hoverboard#301]
In my site I use zoom 18 for the map. The older site used `google-map` component, the new one uses `good-map`:
![screenshot_2017-08-27_12-54-43](https://user-images.githubusercontent.com/744949/29753578-07996d7c-8b29-11e7-9be5-ff288a2e91c3.png)
As you can see the streets are not visible.

**Comment by ozasadnyy** [comment]
@MrCsabaToth it works as designed. We prefer to show global map instead of zoomed one, but you can adjust options as you like: https://github.com/gdg-x/hoverboard/blob/hoverboard-v2/src/elements/map-block.html#L150
Google docs: https://developers.google.com/maps/documentation/javascript/style-reference

**Comment by MrCsabaToth** [comment]
Ooops! Thanks for the heads up. I should have read the source code more.
