### ISSUE TITLE
calendar-plus icon is not seen in fab of session detail

### ISSUE THREAD

**Issue by sembozdemir** [gdg-x/hoverboard#345]
We use v1.2.0 of hoverboard for GDG DevFest Izmir 2017 website. calendar-plus icon is not seen like screenshot below.

![session-detail-image](https://i.imgur.com/bD5ELXv.png)

URL for this page: https://gdgizmir.org/schedule/day1?sessionId=103
URL for github fork: https://github.com/gdgizmir/hoverboard

It is working on hoverboard [demo website](https://hoverboard-master.firebaseapp.com/schedule/day1). But, somethings is wrong in our website. I don't understand the reason.

### Expected Outcome

calendar-plus icon should be visible on session-detail screen properly.

### Actual Outcome

calendar-plus icon is not seen on session-detail screen.

### Steps the reproduce

1. Go gdgizmir.org
2. Navigate schedule page and click one of sessions
3. See calendar-plus icon is not seen properly in fab.

**Comment by sophieH29** [comment]
Hello @sembozdemir 
This happens because you've set a primary text color #FFFFF (white) in [shared-styles.html](https://github.com/gdgizmir/hoverboard/blob/df17/src/styles/shared-styles.html#L17).
And iron-icon style has ``` color: inherit; ``` So it's white, that's why you don't see it.

In hoverboard master we use
``` --text-primary-color:       #212121; ```

You can fix your case by setting 
```
paper-fab iron-icon { color: #212121; }
```
